pluginManagement {
    repositories {
        // TODO: mavenLocal() is here for a patched architectury-loom (fixes unobfuscated Forge on 26.x,
        //  see https://github.com/architectury/architectury-loom/pull/349) - remove once that's merged and released.
        mavenLocal()
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        gradlePluginPortal()
        maven { url "https://files.minecraftforge.net/maven/" }
        maven { url "https://jitpack.io" }
    }
}

if (JavaVersion.current().ordinal() + 1 < 21) {
    throw new IllegalStateException("Please run gradle with Java 21+!")
}

include("common")
include("fabric")
include("forge")
include("neoforge")

rootProject.name = 'cloth-config'
